name: Check SQL Patterns

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Detect changed SQL files
        id: detect
        run: |
          git fetch --no-tags origin ${{ github.base_ref }}
          sql_files=$(git diff origin/${{ github.base_ref }} --name-only --diff-filter=d -- '*.sql')
          echo "$sql_files" > changed_sql_files.txt

      - name: Check disallowed SQL patterns
        run: |
          target_files=$(
            for file in $(cat changed_sql_files.txt); do
              [[ ! -f "$file" ]] && continue
              grep -q -F "$file" ignore_sql_statement_check.conf 2>/dev/null && continue
              grep -qiE 'CREATE\s+VIEW' "$file" && continue
              echo "$file"
            done
          )

          if [[ -z "$target_files" ]]; then
            echo "✅ No target SQL files to check."
            exit 0
          fi

          err=0
          for f in $target_files; do
            if grep -iqE "DROP\s+TABLE|CURRENT_DATE|CURRENT_TIME|CURRENT_TIMESTAMP" "$f"; then
              echo "::error file=$f::❌ Disallowed SQL pattern detected"
              err=1
            fi
          done

          [ $err -eq 1 ] && exit 1
          echo "✅ All checked SQL files passed."