name: Check SQL Patterns

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2 # v4.2.2

      - name: Detect changed SQL files
        id: detect
        run: |
          git fetch --no-tags origin main
          sql_files=$(git diff origin/main --name-only --diff-filter=d -- '*.sql')
          echo "$sql_files" > changed_sql_files.txt

      - name: Check disallowed SQL patterns
        run: |
          target_files=$(
            for file in $(cat changed_sql_files.txt); do
              [[ ! -f "$file" ]] && continue
              grep -q -F "$file" ignore_sql_statement_check.conf 2>/dev/null && continue
              grep -qiE 'CREATE(\s+OR\s+REPLACE)?\s+VIEW' "$file" && continue
              echo "$file"
            done
          )

          echo "🔍 Target files to check:"
          echo "$target_files"


          if [[ -z "$target_files" ]]; then
            echo "✅ No target SQL files to check."
            exit 0
          fi

          err=0

          while IFS= read -r f; do
            # マッチした禁止パターンを抽出
            match=$(grep -oiE "DROP\s+TABLE|CURRENT_DATE|CURRENT_TIME|CURRENT_TIMESTAMP" "$f" || true)
            if [[ -n "$match" ]]; then
              echo "::error file=$f::❌ Disallowed SQL pattern detected: $match"
              err=1
            fi
          done <<< "$target_files"

          [ $err -eq 1 ] && exit 1
          echo "✅ All checked SQL files passed."