name: Check SQL Patterns

on:
  push:
    paths:
      - '**/*.sql'
  pull_request:
    paths:
      - '**/*.sql'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check disallowed SQL patterns
        run: |
          set -euo pipefail

          echo "Filtering target SQL files..."

                    target_files=$(
            for file in $(cat changed_sql_files.txt); do
              [[ ! -f "$file" ]] && continue
              grep -q -F "$file" ignore_sql_statement_check.conf 2>/dev/null && continue
              grep -qiE 'CREATE\s+VIEW' "$file" && continue
              echo "$file"
            done
          )

          if [[ -z "$target_files" ]]; then
            echo "✅ No target SQL files to check."
            exit 0
          fi

          err=0
          for f in $target_files; do
            if grep -iqE "DROP\s+TABLE|CURRENT_DATE|CURRENT_TIME|CURRENT_TIMESTAMP" "$f"; then
              echo "::error file=$f::❌ Disallowed SQL pattern detected"
              err=1
            fi
          done

          [ $err -eq 1 ] && exit 1
          echo "✅ All checked SQL files passed."